
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rectangler
  labels:
    app: rectangler
spec:
  selector:
    matchLabels:
      app: rectangler
  template:
    metadata:
      labels:
        app: rectangler
    spec:
      containers:
      - name: rectangler
        image: rectangler
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: rectangler
  labels:
    app: rectangler
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: rectangler
