
apiVersion: apps/v1
kind: Deployment
metadata:
  name: muxer
  labels:
    app: muxer
spec:
  selector:
    matchLabels:
      app: muxer
  template:
    metadata:
      labels:
        app: muxer
    spec:
      containers:
      - name: muxer
        image: muxer
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: muxer
  labels:
    app: muxer
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: muxer
