apiVersion: apps/v1
kind: Deployment
metadata:
  name: red
  labels:
    app: red
spec:
  selector:
    matchLabels:
      app: red
  template:
    metadata:
      labels:
        app: red
        tier: web
    spec:
      containers:
      - name: red
        image: red
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: red
  labels:
    app: red
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: red
