
apiVersion: apps/v1
kind: Deployment
metadata:
  name: glitch
  labels:
    app: glitch
spec:
  selector:
    matchLabels:
      app: glitch
  template:
    metadata:
      labels:
        app: glitch
    spec:
      containers:
      - name: glitch
        image: glitch
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: glitch
  labels:
    app: glitch
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: glitch
