
apiVersion: apps/v1
kind: Deployment
metadata:
  name: color
  labels:
    app: color
spec:
  selector:
    matchLabels:
      app: color
  template:
    metadata:
      labels:
        app: color
    spec:
      containers:
        - name: color
          image: color
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: color
  labels:
    app: color
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: color
